### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [Diesdooi/naoolheparatras#1]
Olá, @Diesdooi 

Gostaría de traduzir o cenário para o espanhol. Tem pensada alguma actualizaçâo? Em caso contrário, vou comenzar a traduzâo na próxima semana.

**Comment by vidimus** [comment]
Já comencéi o travalho!

**Comment by Diesdooi** [comment]
Hi, Vidimus

I will uptade some typing corrections. I Will try do It today.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vidimus** [comment]
> Hi, Vidimus I will uptade some typing corrections. I Will try do It today. Obter o Outlook para Android<https://aka.ms/AAb9ysg>
> […](#)

OK!

**Comment by Diesdooi** [comment]
Done!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vidimus** [comment]
I'm now testing the translation. I will send you the file in a couple of days, I guess

**Comment by Diesdooi** [comment]
Ok, thanks

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vidimus** [comment]
Translation is here, @Diesdooi 

https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/tree/master/No%20mires%20hacia%20atr%C3%A1s

In order to make things easier in Github, I've edited the audio and recompress it, the two ambient sounds that were too heavy. Reported bug with fire door has been solved and music audios for the intro and ending are too included (awaiting for a incoming voiceover version).

Would you mind to upload the files to your repository?

Obrigado.

**Comment by Diesdooi** [comment]
Certo, farei isso assim que possível.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vidimus** [comment]
> Certo, farei isso assim que possível. 

Ótimo.

**Comment by vidimus** [comment]
Olà, há algum problema com a nova versão? Ainda não estou a ver a actualização em espanhol?
